//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlignTaiko.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlignTaiko.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AlignTaiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create backup before overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackupEnabled {
            get {
                return ResourceManager.GetString("BackupEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch process will be applied to the following difficulties. Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmBatchPrefix {
            get {
                return ResourceManager.GetString("ConfirmBatchPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will overwrite the original .osu file(s). Continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done (files processed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoneBatch {
            get {
                return ResourceManager.GetString("DoneBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done (objects changed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoneSingle {
            get {
                return ResourceManager.GetString("DoneSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag &amp; drop .osu here (or click to browse) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropHint {
            get {
                return ResourceManager.GetString("DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInputNotFound {
            get {
                return ResourceManager.GetString("ErrorInputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputHintBatch {
            get {
                return ResourceManager.GetString("InputHintBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input file name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputHintSingle {
            get {
                return ResourceManager.GetString("InputHintSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open backup folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenBackupFolder {
            get {
                return ResourceManager.GetString("OpenBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select any .osu file in the target folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectBatchSeedFile {
            get {
                return ResourceManager.GetString("SelectBatchSeedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select an .osu file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectInputFile {
            get {
                return ResourceManager.GetString("SelectInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a folder containing .osu files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectInputFolder {
            get {
                return ResourceManager.GetString("SelectInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
    }
}
